kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-nexus-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-nexus-storage
  claimRef:
    name: nexus-pv-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /nexus-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube-m02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  namespace: devops-tools
spec:
  storageClassName: local-nexus-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
