pipeline {
	agent {
 		any
	}

	environment {
	
	}

	stages{
		stage("Build"){
			agent {
        		        docker { 
                			image 'maven:3.9.0-eclipse-temurin-11'
                	 	}
            		}
			steps{
				// With tests passed build and package the app
				sh 'mvn -f sample-maven-web-app/pom.xml clean install'
			}
		}	
	}
}
