pipeline {
	agent {
		kubernetes {
			inheritFrom "kube-agent"
            cloud "kubernetes"
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              namespace: default
              labels:
                jenkins: slave
            spec:
              containers:
              - name: jnlp
                image: jenkins/inbound-agent:latest
                args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
              - name: maven
                image: maven:3.8.7-openjdk-18-slim
                command:
                - sleep
                args:
                - 99d
            '''
		}
	}
	environment {
		TEST = 'test'
	}
	stages{
		stage("Build"){
			steps{
				container('maven'){
					// With tests passed build and package the app
					sh 'mvn -f sample-maven-web-app/pom.xml clean install'
				}
			}
		}	
	}
}
